# Exercises Day 3 


Created by Julia Kukulies for **Advanced Scientific Programming with Python** 

## Numpy exercises 

In [2]:
import numpy as np

**1a)**

In [9]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**1b)**

In [11]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**1c)**

In [13]:
reverse= a[::-1]
print(reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**1d)**

In [17]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**1e)**

In [24]:
a= np.array([1,2,0,0,4,0])
indices=np.where(a == 0)
print(indices)

(array([2, 3, 5]),)


**1f)**

In [101]:
mean = np.mean(np.random.random(30))
print(mean)

0.4418707926792758


**1g)**

In [47]:
a = np.zeros((10,10))
a[:,0] = 1
a[:,-1] = 1
a[0,:] = 1
a[-1,:] = 1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**1h)**

In [68]:
checkerboard= np.zeros((8,8)) 
checkerboard[::2,1::2] = 1
checkerboard[1::2,::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**1i)**

In [111]:
a = np.array(([0,1], [1,0]))
checkerboard = np.tile(a,(4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**1j)**

In [82]:
Z = np.arange(11)
Z[3:9] -= Z[3:9]*2
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


**1k)**

In [85]:
Z = np.random.random(10)
Z_sorted = np.sort(Z)
print(Z_sorted)

[0.15990741 0.19691312 0.24925074 0.31794548 0.33329389 0.36026393
 0.57596899 0.64053547 0.94505615 0.9828424 ]


**1l)**

In [88]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

False


**1m)**

In [92]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z= Z.astype('float32')
print(Z.dtype)

int32
float32


**1n)**

In [100]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diagonal(C)
print(D)

[ 18  66 132]


## 2. Speed optimization using NumPy


Here is the optimized code for the matrix multiplication from matmult.py (https://github.com/uu-python/day2-bestpractices-1/blob/master/matmult.py ):

1. define function 
2. use existing numpy functions instead of appending values to an empty list 

In [129]:
def matmult(N):
    # create matrix NxN random matrix 
    X = np.random.randint(1000, size = (N,N))

    # create matrix NxN+1 random matrix 
    Y = np.random.randint(1000, size = (N,N+1))

    # perform matrix multiplication 
    result = np.matmul(X,Y)
    
    return result 


In [130]:
N = 250 
result = matmult(N)

##  3. Examples on classes and inheritance in Python 

Note: I show here the definition of the classes. But the classes are also defined in the module classroom.py

**a) Person class **

In [5]:
class Person(object):
    def __init__(self, firstname, lastname):
        self.firstname = firstname 
        self.lastname = lastname 
    def get_full_name(self):
        full_name = self.firstname + ' '+  self.lastname
        return full_name

In [153]:
person = Person('Julia', 'Kukulies')
full_name = person.get_full_name()
print(full_name)

Julia Kukulies


**b) Student class ( = child class from Person) **

In [185]:
class Student(Person):
    def __init__(self, firstname, lastname, subject):
        Person.__init__(self, firstname, lastname)
        self.subject = subject 
    def printNameSubject(self):
        print(self.firstname+ ' ' + self.lastname + ', '+ self.subject)

In [190]:
from classroom import Student 

me= Student('Julia', 'Kukulies', 'Climate Science')
me.printNameSubject()

Julia Kukulies, Climate Science


**c) Teacher class**

In [12]:
class Teacher(Person):
    def __init__(self, firstname, lastname, course):
        Person.__init__(self, firstname, lastname)
        self.course = course
    def printNameCourse(self):
        print(self.firstname+ ' ' + self.lastname + ', '+ self.course)

In [1]:
from classroom import Teacher

teacher = Teacher('Minerva', 'McGonagall', 'Transfiguration')
teacher.printNameCourse()

Minerva McGonagall, Transfiguration
